### PR TITLE
Add DAITA V2 support

### PR DESCRIPTION
**Pull request by dlon**
Main changes:
* Add per-machine timers.
* Make padding and blocking fractions configurable (i.e. https://docs.rs/maybenot/2.0.1/maybenot/struct.Machine.html#structfield.allowed_padding_packets).
* Handle tunnel recv and send events.
* Implement `replace` flag for padding packets.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18)

### CODE REVIEW

**Review by Serock3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`device/daita.go` line 33 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OB6RcEf0jJNcOsoouxi:-OB6RcEf0jJNcOsoouxj:b-hoyr5n) ([raw file](https://github.com/mullvad/wireguard-go/blob/2264ad18fcb27d86c41b72bc180b08ace50878c6/device/daita.go#L33)):*
> ```Go
> 
> type MachineTimer struct {
> 	started time.Time
> ```

Are you sure that you need to store the start time and the duration in the `MachineTimer`? Maybe you could store just the end time?
___
*[`device/daita.go` line 302 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OB6QZh82KL911qYafBi:-OB6QZh93VixKkvVSWrx:bfxxpcx) ([raw file](https://github.com/mullvad/wireguard-go/blob/2264ad18fcb27d86c41b72bc180b08ace50878c6/device/daita.go#L302)):*
> ```Go
> 			startNewTimer := false
> 
> 			if timerWasQueued {
> ```

Is this if statement correct? Should it not be `if !timerWasQueued {...}`

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`device/daita.go` line 33 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OB6RcEf0jJNcOsoouxi:-OB9x7rWAk5xVINlrgxK:b9ekhpm) ([raw file](https://github.com/mullvad/wireguard-go/blob/2264ad18fcb27d86c41b72bc180b08ace50878c6/device/daita.go#L33)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Are you sure that you need to store the start time and the duration in the `MachineTimer`? Maybe you could store just the end time?
</blockquote></details>

You definitely could. You lose some information (the duration), but we don't need it, I suppose.
___
*[`device/daita.go` line 302 at r1](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OB6QZh82KL911qYafBi:-OB9x5Oq-mtzHW7aYo6f:b-9dgq9d) ([raw file](https://github.com/mullvad/wireguard-go/blob/2264ad18fcb27d86c41b72bc180b08ace50878c6/device/daita.go#L302)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Is this if statement correct? Should it not be `if !timerWasQueued {...}`
</blockquote></details>

Done. (In one of the fixup commits)

**Review by Serock3 — CHANGES_REQUESTED** [review]
We may have discussed this previously, but alternatively we could put the `outboundPackets` and `replacedPackets` in `peer.daita`. That would potentially have the effect of slightly improving performance when daita is off, and worsening it when it  is enabled. Thoughts?

> Reviewed 5 of 5 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18#-:-OBPjMIa9fn_bZYSImLb:b5ox15a)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`device/peer.go` line 289 at r10](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBPhwnD63URVGS7qk8L:-OBPhwnD63URVGS7qk8M:b-s9xr8j) ([raw file](https://github.com/mullvad/wireguard-go/blob/df59f9039527fc5eb2cf8b9961993b3039a363b8/device/peer.go#L289)):*
> ```Go
> func (peer *Peer) OutboundPacketsDec() {
> 	if peer.outboundPackets.Add(-1) < 0 {
> 		peer.device.log.Errorf("queuedPackets underflow")
> ```

It's a bit uncomfortable that this could fail silently, but I'm not sure if there are any better ways to do it. I guess we could close the tunnel, or just close down `peer.daita`. Opinions?
___
*[`device/daita.go` line 350 at r11](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBPmjFAEj4uNkW57VZK:-OBPmjFAEj4uNkW57VZL:b3aevez) ([raw file](https://github.com/mullvad/wireguard-go/blob/b7d544987734ef596a02732bd8ddec56b322e781/device/daita.go#L350)):*
> ```Go
> 				// Replace timer if it (should have) already fired
> 				// or if the action duration is greater than the time left
> 				startNewTimer = timer.completeAt.Before(now) || (action.Duration > timer.completeAt.Sub(now))
> ```

I think the `timer.completeAt.Before(now)` part is redundant. It can be rewritten as,  `0 > timer.completeAt.Sub(now)`, and since `action.Duration` can't be negative it is implied.
___
*[`device/daita.go` line 400 at r11](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBQ5TYF-_32Agk18x9F:-OBQ5TYF-_32Agk18x9G:bimzxwf) ([raw file](https://github.com/mullvad/wireguard-go/blob/b7d544987734ef596a02732bd8ddec56b322e781/device/daita.go#L400)):*
> ```Go
> 	var actionsWritten C.uintptr_t
> 
> 	firstElem := (*C.MaybenotEvent)(unsafe.Pointer(&daita.eventsCBuf[0]))
> ```

What happened to `unsafeSliceData`? Should we not use that?

**Review by dlon — COMMENTED** [review]
I believe it has a negligible impact on performance, so I favor the simplest (current) solution.

> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18#-:-OBQMalO6Crg1T-RniFC:b8dy8sx)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`device/daita.go` line 350 at r11](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBPmjFAEj4uNkW57VZK:-OBQPPezEBz1xb-0DWu7:b-896fix) ([raw file](https://github.com/mullvad/wireguard-go/blob/b7d544987734ef596a02732bd8ddec56b322e781/device/daita.go#L350)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I think the `timer.completeAt.Before(now)` part is redundant. It can be rewritten as,  `0 > timer.completeAt.Sub(now)`, and since `action.Duration` can't be negative it is implied.
</blockquote></details>

Done.
___
*[`device/daita.go` line 400 at r11](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBQ5TYF-_32Agk18x9F:-OBQQ0pH5wqF7uxSNgTz:bl7e66f) ([raw file](https://github.com/mullvad/wireguard-go/blob/b7d544987734ef596a02732bd8ddec56b322e781/device/daita.go#L400)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

What happened to `unsafeSliceData`? Should we not use that?
</blockquote></details>

Done. I think they're equivalent in this case, but maybe it's a bit cleaner.
___
*[`device/peer.go` line 289 at r10](https://reviewable.io/reviews/mullvad/wireguard-go/18#-OBPhwnD63URVGS7qk8L:-OBQPaGB-yCdXfTgAnVm:b-dbhuh3) ([raw file](https://github.com/mullvad/wireguard-go/blob/df59f9039527fc5eb2cf8b9961993b3039a363b8/device/peer.go#L289)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

It's a bit uncomfortable that this could fail silently, but I'm not sure if there are any better ways to do it. I guess we could close the tunnel, or just close down `peer.daita`. Opinions?
</blockquote></details>

I lean towards *either* resetting the counter to 0 or simply panicking.

**Review by Serock3 — APPROVED** [review]
Alright, I agree

> Reviewed 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/18#-:-OBQWOPn3IsLOvOmcRHT:bbngwwl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dlon)

**Pull request merged**
