### PR TITLE
Drop virtual network packets when overflowing

### PR DESCRIPTION
**Pull request by pinkisemils**
When netstack issues any kind of a write to a network, it acquires a lock. The lock is held until a write finishes. While the lock is held, calls to `Close` will block. When a wireguard device is being shut down, it stops reading from the underlying tunnel device, and tries to call `Close` on it. This can create a deadlock. To relieve this, I have changes the netstack `Tun` implementation to drop packets when they cannot be received, and introduced slight buffering - will buffer 1000 packets before dropping them. Whilst dropping packets is not great, it is better than blocking or buffering further. Since these packets operate at layer 3, it is also not unreasonable to drop them since it is appropriate for the spec. Further, this code will be used exclusively on iOS for sending ICMP traffic to the relay and negotiating ephemeral peers - so no real user traffic will end up being dropped.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/19)

### CODE REVIEW

**Review by acb-mv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @buggmagnet, @dlon, and @Serock3)

**Review by Serock3 — APPROVED** [review]
:lgtm: Though another pattern I have seen is to have a `closed  chan struct{}`, which would be waited on the above select statement instead of the `default` branch.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/19#-:-ODCIHhxA7KXZZkydk-P:begxshy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @buggmagnet and @dlon)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/19#-:-ODCIxQy4UWWryyY9Kf2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dlon)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-go/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pinkisemils)

**Pull request merged**
